issuer: https://token.actions.githubusercontent.com
subject: repo:shopwell-shop/octo-sts-action:pull_request
claim_pattern:
  workflow_ref: shopwell-shop/octo-sts-action/\.github/workflows/use-action\.yaml@refs/heads/main

permissions:
  contents: read
